### ISSUE TITLE
Forge Mod Loader Has Found A Duplacte Mod Within Your System

### ISSUE THREAD

**Issue by Doglover2185** [Chicken-Bones/CodeChickenCore#112]
Hi Whenever I Download The Latest 1.7.10 Code Chiken Core To My Modpack Needed For Some Of The Mods It Says This: Forge Mod Loader Has Found A Proplem With Your Minecraft Installation You Have Mod Sources That Are Duplacite Within Your System Mod Id : File name CodeChickenCore : minecraft.jar and any time i deleate the duplacte it crashes before even starting to load with exit code 0 Please Help Me Fix This 
![image](https://user-images.githubusercontent.com/98370261/153015014-35cc153d-02c4-4b33-81cd-1c01166510eb.png) Theres The Image If That Helps

**Comment by Doglover2185** [comment]
Also If I Remove A Mod Thats Supposed To Fix Crashing From It I Get This "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/multipart/TMultiPart
Exit Code: -1" And Heres The Crash Report "---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2/8/22 10:33 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/multipart/TMultiPart
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/multipart/TMultiPart
	at thut.tech.common.blocks.lift.BlockLift.<init>(BlockLift.java:69)
	at thut.tech.common.handlers.BlockHandler.registerBlocks(BlockHandler.java:29)
	at thut.tech.common.TechCore.preInit(TechCore.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.multipart.TMultiPart
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1660570192 bytes (1583 MB) / 3172466688 bytes (3025 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{2.1.12-GTNH} [Not Enough Items] (NotEnoughItems-1.7.10-2.1.12-GTNH-universal.jar) 
	UCH	securitycraft{v1.8.13} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.13.jar) 
	UCH	ActuallyAdditions{1.7.10-r21} [Actually Additions] (ActuallyAdditions-1.7.10-r21.jar) 
	UCH	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UCH	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCH	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCH	BackTools{4.0.0} [BackTools] (BackTools-4.0.0.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	baublelicious{1.7.10-1.2.2-final} [Baublelicious] (baublelicious-1.7.10-1.2.2-final.jar) 
	UCH	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCH	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCH	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCH	chancecubes{1.7.10-2.4.1.0} [Chance Cubes] (ChanceCubes-1.7.10-2.4.1.182.jar) 
	UCH	ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
	UCH	controlling{1.0.0} [Controlling] (Controlling-1.7.10-1.0.0.jar) 
	UCH	cosmeticarmorreworked{1.7.10-v6b} [CosmeticArmorReworked] (CosmeticArmorReworked-1.7.10-v6b.jar) 
	UCH	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCH	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCH	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCH	doggytalents{1.14.2.317} [Doggy Talents] (DoggyTalents-1.7.10-1.14.2.317-universal.jar) 
	UCH	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCH	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCH	waterhooks{1.2.1} [Water Hooks] (waterhooks-1.2.1.jar) 
	UCH	enderioaddons{0.10.13} [Ender IO Addons] (EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.13.56_beta.jar) 
	UCH	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCH	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCH	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCH	FoodExpansion{1.0} [Food Expansion] (FoodExpansion1.1.1-mc1.7.10.jar) 
	UCH	goodnightsleep{0.0.2} [Good Night's Sleep] (good-nights-sleep-1.7.10-v0.0.2.jar) 
	UCH	gravestone{0.7.10.3} [Gravestone] (GraveStone Mod 0.7.10.3.jar) 
	UCH	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCH	InventoryPets{1.5.2} [Inventory Pets] (inventorypets-1.7.10-1.5.2-universal.jar) 
	UCH	ironfurnaces{1.2.4} [Iron Furnaces] (ironfurnaces-1.2.4R.jar) 
	UCH	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCH	kleeslabs{1.0} [KleeSlabs] (kleeslabs-mc1.7.10-1.2.9.jar) 
	UCH	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCH	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCH	magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury] (magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCH	mo{0.4.2} [Matter Overdrive] (MatterOverdrive-1.7.10-0.4.2.jar) 
	UCH	mininghats{1.3} [Mining Hats] (mininghats-1.3.jar) 
	UCH	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCH	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCH	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCH	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.0-1.jar) 
	UCH	netheriteplus{0.9 Beta} [NetheritePlus+] (NetheritePlus_1.7.10_Beta0.9.jar) 
	UCH	oreexcavation{1.1.134} [OreExcavation] (OreExcavation-1.1.134.jar) 
	UCH	PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6-fix-1.jar) 
	UCH	ProjectE{1.7.10-PE1.10.1} [ProjectE] (ProjectE-1.7.10-PE1.10.1.jar) 
	UCH	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCH	sit{v1.1} [Sit] (sit-1.7.10-v1.1.jar) 
	UCH	spark{1.6.4} [spark] (spark-forge1710.jar) 
	UCH	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCE	thutcore{2.0} [ThutCore] (ThutMods-2.0.jar) 
	UCE	ThutConcrete{2.0.0} [Thut's Concrete] (ThutMods-2.0.jar) 
	UCE	ThutTech{2.0.0} [Thut's Tech] (ThutMods-2.0.jar) 
	UCH	tumbleweed{1.7.10-0.2} [Tumbleweed] (tumbleweed-1.7.10-0.2.jar) 
	UCH	TwilightForest{2.3.8dev} [The Twilight Forest] (twilightforest-1.7.10-2.3.8.jar) 
	UCH	ViewEMC{v4} [View EMC] (ViewEMC-1.7.10-v4.jar) 
	UCH	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCH	wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
	UCH	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCH	waystones{1.0.12} [Waystones] (Waystones-mc1.7.10-1.0.12.jar) 
	UCH	wolfarmor{1.3.0} [Wolf Armor and Storage] (wolfarmor-1.3.0.1.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 730/PCIe/SSE2'
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from EnderIO-1.7.10-2.3.0.429_beta.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it." Please Help
