### ISSUE TITLE
1.8.9 Thaumic Tinkerer crash during launch

### ISSUE THREAD

**Issue by Atomo93** [Chicken-Bones/CodeChickenCore#114]
01:43:34.460
FML
main
An error occurred trying to configure the minecraft home at C:\Users\Diego\AppData\Roaming\.minecraft for Forge Mod Loader
java.lang.RuntimeException: java.lang.NoSuchFieldException: loadedCoremods
	at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:552)
	at codechicken.core.launch.DepLoader$DepLoadInst.activateDeps(DepLoader.java:502)
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:496)
	at codechicken.core.launch.DepLoader.load(DepLoader.java:684)
	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:577)
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416)
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldException: loadedCoremods
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:539)
	... 18 more
01:43:34.471
LaunchWrapper
main
Unable to launch
java.lang.RuntimeException: java.lang.NoSuchFieldException: loadedCoremods
	at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:552)
	at codechicken.core.launch.DepLoader$DepLoadInst.activateDeps(DepLoader.java:502)
	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:496)
	at codechicken.core.launch.DepLoader.load(DepLoader.java:684)
	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:577)
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:416)
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:246)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:95)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:72)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:119)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldException: loadedCoremods
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at codechicken.core.launch.DepLoader$DepLoadInst.searchCoreMod(DepLoader.java:539)
	... 18 more
01:43:34.473
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
01:43:34.473
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
01:43:34.473
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
01:43:34.473
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
01:43:34.473
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
01:43:34.474
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
01:43:34.474
STDERR
main
[java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
01:43:35.588
launcher
main

01:43:35.588
monitor
Process Monitor
Process crashed with exit code 1

**Comment by Atomo93** [comment]
It launched without CodeChickenCore, just ...lib one. But the erros continue, are them really a thing or not?
Where do I can download the lib jar for 1.8 or minus?

16:44:55.757
Config
Client thread
[OptiFine] Animated sprites: 72
16:44:56.350
FML
Client thread
Exception loading model for variant thaumcraft:barrier#normal
java.lang.Exception: Could not load model definition for variant thaumcraft:barrier#normal
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:211)
	at net.minecraft.client.resources.model.ModelBakery.func_177591_a(ModelBakery.java:113)
	at net.minecraftforge.client.model.ModelLoader.loadBlocks(ModelLoader.java:166)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:111)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:732)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:326)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Encountered an exception when loading model definition of model thaumcraft:blockstates/barrier.json
	at net.minecraft.client.resources.model.ModelBakery.func_177586_a(ModelBakery.java:170)
	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:207)
	... 17 more
Caused by: java.io.FileNotFoundException: thaumcraft:blockstates/barrier.json
	at net.minecraft.client.resources.FallbackResourceManager.func_135056_b(FallbackResourceManager.java:93)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_135056_b(SimpleReloadableResourceManager.java:78)
	at net.minecraft.client.resources.model.ModelBakery.func_177586_a(ModelBakery.java:148)
	... 18 more
16:44:56.351
FML
Client thread
Model definition for location thaumictinkerer:boundJar#colour=blue,type=brain not found
16:44:56.351
FML
Client thread
Model definition for location thaumictinkerer:boundJar#colour=red,type=void not found
16:44:56.351
FML
Client thread
Model definition for location thaumictinkerer:boundJar#colour=light_blue,type=brain not found
16:44:56.351
FML
Client thread
Model definition for location thaumictinkerer:boundJar#colour=lime,type=brain not found
16:44:56.351
FML
Client thread
Model definition for location thaumcraft:eldritch#type=lock not found
16:44:56.352
FML
Client thread
Model definition for location thaumcraft:infernal_furnace#inventory not found
16:44:56.352
FML
Client thread
Model definition for location thaumcraft:eldritch#type=teleporter not found
16:44:56.352
FML
Client thread
Suppressed additional 9 model loading errors for domain thaumcraft
16:44:56.352
FML
Client thread
Suppressed additional 33 model loading errors for domain thaumictinkerer
16:44:56.585
net.optifine.Log
Client thread
[OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
16:44:56.671
Config
Client thread
[OptiFine] *** Reloading custom textures ***
16:44:56.759
Config
Client thread
[OptiFine] Enable face culling: acacia_leaves, birch_leaves, dark_oak_leaves, jungle_leaves, oak_leaves, spruce_leaves

**Comment by Atomo93** [comment]
When oppening or creating a world

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  ShoulderPlugin (ShoulderSurfing-1.8.9-2.2.2.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.88.jar)
  IC2core (industrialcraft-2-2.3.262-ex18.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 7/10/22 10:05 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.minecraft.client.settings.GameSettings.func_100015_a(GameSettings.java:369)
	at net.minecraft.client.renderer.EntityRenderer.func_78481_a(EntityRenderer.java:650)
	at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:941)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1619)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1587)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.minecraft.client.settings.GameSettings.func_100015_a(GameSettings.java:369)
	at net.minecraft.client.renderer.EntityRenderer.func_78481_a(EntityRenderer.java:650)
	at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:941)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1619)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1587)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Atomo93'/555, l='MpServer', x=217.50, y=64.00, z=247.50]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 226.00,64.00,254.00 - World: (226,64,254), Chunk: (at 2,4,14 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 95 game time, 95 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 53 total; [EntityItem['item.item.actuallyadditions.itemMiscCanola'/256, l='MpServer', x=255.13, y=65.00, z=244.47], EntityItem['item.item.actuallyadditions.itemCanolaSeed'/257, l='MpServer', x=255.84, y=65.00, z=244.63], EntityBat['Bat'/258, l='MpServer', x=242.81, y=32.34, z=305.41], EntityZombie['Zombie'/644, l='MpServer', x=217.50, y=21.00, z=172.50], EntityCreeper['Creeper'/137, l='MpServer', x=168.50, y=34.00, z=178.50], EntityAuraNode['Aura Node'/145, l='MpServer', x=175.50, y=75.50, z=228.50], EntityBat['Bat'/146, l='MpServer', x=164.31, y=27.06, z=243.50], EntityAuraNode['Aura Node'/147, l='MpServer', x=171.50, y=63.50, z=283.50], EntitySquid['Squid'/148, l='MpServer', x=171.56, y=61.50, z=281.88], EntityAuraNode['Aura Node'/20, l='MpServer', x=114.50, y=63.50, z=195.50], EntitySquid['Squid'/149, l='MpServer', x=165.38, y=60.84, z=272.97], EntitySquid['Squid'/150, l='MpServer', x=167.00, y=60.72, z=273.59], EntitySquid['Squid'/278, l='MpServer', x=274.78, y=60.88, z=184.75], EntitySquid['Squid'/151, l='MpServer', x=163.66, y=61.44, z=272.09], EntitySquid['Squid'/281, l='MpServer', x=277.75, y=61.16, z=186.19], EntityCreeper['Creeper'/288, l='MpServer', x=292.50, y=59.00, z=291.50], EntityCreeper['Creeper'/289, l='MpServer', x=289.50, y=59.00, z=291.50], EntityAuraNode['Aura Node'/178, l='MpServer', x=179.50, y=64.50, z=164.50], EntitySquid['Squid'/179, l='MpServer', x=189.91, y=53.47, z=189.25], EntitySquid['Squid'/180, l='MpServer', x=189.34, y=53.84, z=187.72], EntityPlayerSP['Atomo93'/555, l='MpServer', x=217.50, y=64.00, z=247.50], EntitySquid['Squid'/181, l='MpServer', x=183.91, y=55.16, z=184.72], EntitySquid['Squid'/182, l='MpServer', x=187.72, y=53.72, z=188.25], EntitySquid['Squid'/183, l='MpServer', x=187.44, y=54.78, z=185.72], EntitySquid['Squid'/184, l='MpServer', x=187.25, y=55.84, z=191.53], EntityFallingBlock['Falling Block'/570, l='MpServer', x=285.50, y=15.41, z=232.50], EntityFallingBlock['Falling Block'/573, l='MpServer', x=286.50, y=15.41, z=232.50], EntitySpider['Spider'/701, l='MpServer', x=198.50, y=43.00, z=255.50], EntityFallingBlock['Falling Block'/578, l='MpServer', x=285.50, y=14.41, z=233.50], EntityAuraNode['Aura Node'/196, l='MpServer', x=186.50, y=67.50, z=264.50], EntityZombie['Zombie'/197, l='MpServer', x=178.50, y=28.00, z=278.50], EntityZombie['Zombie'/198, l='MpServer', x=179.50, y=28.00, z=275.50], EntityZombie['Zombie'/199, l='MpServer', x=178.50, y=28.00, z=275.50], EntityZombie['Zombie'/719, l='MpServer', x=199.50, y=43.00, z=257.50], EntityZombie['Zombie'/92, l='MpServer', x=154.50, y=35.00, z=176.50], EntityZombie['Zombie'/605, l='MpServer', x=247.50, y=39.00, z=324.50], EntitySquid['Squid'/94, l='MpServer', x=154.50, y=47.00, z=214.06], EntityZombie['Zombie'/223, l='MpServer', x=223.50, y=21.00, z=189.50], EntitySquid['Squid'/96, l='MpServer', x=154.78, y=48.84, z=216.50], EntityZombie['Zombie'/224, l='MpServer', x=222.50, y=21.00, z=189.50], EntityAuraNode['Aura Node'/225, l='MpServer', x=209.50, y=70.50, z=201.50], EntityBat['Bat'/97, l='MpServer', x=155.16, y=28.06, z=239.59], EntityAuraNode['Aura Node'/226, l='MpServer', x=218.50, y=63.50, z=218.50], EntityBat['Bat'/98, l='MpServer', x=154.78, y=28.88, z=239.75], EntityAuraNode['Aura Node'/227, l='MpServer', x=221.50, y=64.50, z=287.50], EntityZombie['Zombie'/611, l='MpServer', x=246.50, y=12.00, z=258.50], EntityFallingBlock['Falling Block'/619, l='MpServer', x=293.50, y=9.59, z=322.50], EntityPig['Pig'/241, l='MpServer', x=232.50, y=64.00, z=302.16], EntityPig['Pig'/242, l='MpServer', x=232.50, y=64.00, z=303.53], EntityPig['Pig'/243, l='MpServer', x=232.50, y=65.00, z=306.19], EntityPig['Pig'/244, l='MpServer', x=232.50, y=65.00, z=304.84], EntityBat['Bat'/254, l='MpServer', x=252.28, y=43.13, z=176.59], EntityItem['item.item.seeds'/255, l='MpServer', x=254.47, y=64.00, z=236.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1557132528 bytes (1484 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 19 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4G -Xmx4G -Xmn768m -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:-UsePerfData -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=50 -XX:G1HeapRegionSize=1 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAA	ActuallyAdditions{1.8.9-r26} [Actually Additions] (ActuallyAdditions-1.8.9-r26.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.2004-universal.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCHIJAAAA	craftingtweaks{3.0.55} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.55.jar) 
	UCHIJAAAA	ShetiPhianCore{3.1.2} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.2.jar) 
	UCHIJAAAA	EnderTanks{1.2.2} [EnderTanks] (EnderTanks-1.8.9-1.2.2.jar) 
	UCHIJAAAA	devjg_fullbright{2.1.2} [Fullbright] (FullBright-2.1.2.jar) 
	UCHIJAAAA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.8-32} [Immersive Engineering] (ImmersiveEngineering-0.8-32.jar) 
	UCHIJAAAA	IC2{2.3.262-ex18} [IndustrialCraft 2] (industrialcraft-2-2.3.262-ex18.jar) 
	UCHIJAAAA	JEI{2.28.18.187} [Just Enough Items] (jei_1.8.9-2.28.18.187.jar) 
	UCHIJAAAA	journeymap{1.8.9-5.2.4} [JourneyMap] (journeymap-1.8.9-5.2.4-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.23.jar) 
	UCHIJAAAA	mousetweaks{2.7.1} [Mouse Tweaks] (MouseTweaks-2.7.1-mc1.8.8.jar) 
	UCHIJAAAA	multibeds{1.0.1} [Multi-Beds] (multibeds-1.8.9-1.0.1.jar) 
	UCHIJAAAA	terraqueous{1.0.3} [Terraqueous] (terraqueous-1.8.9-1.0.3.jar) 
	UCHIJAAAA	multistorage{1.0.1} [Multi-Storage] (multistorage-1.8.9-1.0.1.jar) 
	UCHIJAAAA	harvestcraft{1.8.9d} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.8.9e.jar) 
	UCHIJAAAA	platforms{1.0.4} [Platforms] (platforms-1.8.9-1.0.4.jar) 
	UCHIJAAAA	ProjectE{1.8.9-PE1.1.4} [ProjectE] (ProjectE-1.8.9-PE1.1.4.jar) 
	UCHIJAAAA	shouldersurfing{2.2.2} [Shoulder Surfing] (ShoulderSurfing-1.8.9-2.2.2.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
	UCHIJAAAA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJAAAA	thaumicinfusion{4.86} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.88.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	thaumictinkerer{${version}} [Thaumic Tinkerer] (ThaumicTinkerer-3.0-1.8.9-170.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
ShoulderPlugin (ShoulderSurfing-1.8.9-2.2.2.jar)
  com.teamderpy.shouldersurfing.asm.transformers.EntityPlayerRayTrace
  com.teamderpy.shouldersurfing.asm.transformers.EntityRendererGetMouseOver
  com.teamderpy.shouldersurfing.asm.transformers.EntityRendererGetMouseOver2
  com.teamderpy.shouldersurfing.asm.transformers.EntityRendererOrientCamera
  com.teamderpy.shouldersurfing.asm.transformers.EntityRendererRayTrace
thaumicinfusion (ThaumicInfusion-1.8.9-4.88.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
IC2core (industrialcraft-2-2.3.262-ex18.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 22.7.1.220725' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.0 Compatibility Profile Context 22.7.1.220725, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 3200G with Radeon Vega Graphics 
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 22.7.1.220725
	OpenGlRenderer: AMD Radeon(TM) Vega 8 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
