### ISSUE TITLE
java.lang.NullPointerException: Ticking entity crash

### ISSUE THREAD

**Issue by Alaberti** [Chicken-Bones/CodeChickenCore#29]
Crashlog: http://pastebin.com/raw.php?i=S9Q1w1zQ 

Also referenced here: https://github.com/micdoodle8/Galacticraft/issues/1527

CodeChickenCore 1.0.4.35, Forge 1307. Issue occurred repeatedly while on a server walking around and exploring, causing the server to close and require a manual restart.

**Comment by ET-Bent** [comment]
Can relate, same Problem here, using Forge 1352 and CodeChickenCore 1.0.4.35. 

Crash:
```
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at codechicken.lib.world.WorldExtension.unloadChunk(WorldExtension.java:52)
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkUnLoad(WorldExtensionManager.java:67)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_797_WorldExtensionEventHandler_onChunkUnLoad_Unload.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:941)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:342)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Happens randomly while walking around / normal gameplay.

**Comment by ET-Bent** [comment]
Okay we have this problem now for several days and found out that the crashes only occur at specific times. It's always XX:01; XX:11; XX:21; XX:31 [...] this is very strange. Can somebody look into this? This error is not fixable for Mod-packers because the crash logs don't contain information about where nor why (exactly). I would really appreciate your help.

![crash_logs](https://cloud.githubusercontent.com/assets/5788982/7304643/1317331a-e9f9-11e4-8659-458ea614ffb8.png)
