### ISSUE TITLE
ASM Transformer Crash

### ISSUE THREAD

**Issue by DanielHuisman** [Chicken-Bones/CodeChickenCore#47]
I made a coremod using CodeChickenCore / CodeChickenLib, it works fine in my development environment, but after building it crashes during the transformer process. I'm not entirely sure what causes the crash, but I think it has something to do with the deobfuscator. To my knowledge CCC / CCL will handle the changes in class, field and method names, so I can just use deobfuscated names in my ASM transformers. 

My source code: https://github.com/AgeCraft/ExtendedMetadata/blob/master/src/main/java/org/agecraft/extendedmetadata/asm/EMTransformer.java
The full FML log: https://gist.github.com/DanielHuisman/68ddf394ca93d991d976

And the error:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/Block
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.Block
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer org.agecraft.extendedmetadata.asm.EMTransformer@6499fe37 from coremod EMCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.8-11.14.3.1446.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Method not found: [atr.registerBlocks()V]
	at org.agecraft.extendedmetadata.asm.EMTransformer.transform(EMTransformer.java:312) ~[ExtendedMetadata-1.8-1.0.1.0-dev.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.8-11.14.3.1446.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: Method not found: [atr.registerBlocks()V]
	at codechicken.lib.asm.ModularASMTransformer$MethodTransformer.transform(ModularASMTransformer.java:85) ~[CodeChickenLib-1.8-1.1.2.115-universal.jar:?]
	at codechicken.lib.asm.ModularASMTransformer$ClassNodeTransformerList.transform(ModularASMTransformer.java:36) ~[CodeChickenLib-1.8-1.1.2.115-universal.jar:?]
	at codechicken.lib.asm.ModularASMTransformer.transform(ModularASMTransformer.java:283) ~[CodeChickenLib-1.8-1.1.2.115-universal.jar:?]
	at org.agecraft.extendedmetadata.asm.EMTransformer.transform(EMTransformer.java:310) ~[ExtendedMetadata-1.8-1.0.1.0-dev.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.8-11.14.3.1446.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:554) ~[od.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:315) ~[bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
	... 6 more
```

**Comment by Chicken-Bones** [comment]
org.agecraft.extendedmetadata.asm.EMTransformer.transform

**Comment by DanielHuisman** [comment]
That's my transform method, what's up with it?
I know the ModularASMTransformer is called from there, but nothing in my code there should cause the crash.

**Comment by Chicken-Bones** [comment]
Aah, I see. You're using CCL to do some ASM. My apologies for not reading your issue properly and assuming you were just posting a bug report with CCC.

You must use the srg method/field names as the second parameter to ObfMapping if you want them to be obfuscated properly. CCL doesn't carry around the fields.csv or methods.csv in the obfuscated environment for 2 reasons.
1. The mcp mappings can change nightly, so there's no knowing which ones you were using
2. The csv files are fairly large

So yeah, use the srg names. In obf, CCL will use the same method FML uses to map obfuscated -> srg. In mcp, CCL will use the configured conf folder (containing methods.csv and fields.csv) to find the appropriate mcp name for the srg name.

**Comment by DanielHuisman** [comment]
Ok, thanks this fixed the issue.
