### ISSUE TITLE
(1.8, in modding environment) conf folder is missing 'methods.csv'

### ISSUE THREAD

**Issue by sigurd4** [Chicken-Bones/CodeChickenCore#53]
i'm using this directory here:
C:\Users\Sigurd\.gradle\caches\minecraft\net\minecraftforge\forge\1.8-11.14.3.1450\unpacked\conf
and this is my log:

```
[20:02:04] [main/INFO] [GradleStart]: accessToken: modstest
[20:02:04] [main/INFO] [GradleStart]: version: 1.7
[20:02:04] [main/INFO] [GradleStart]: username: sigurd-s@online.no
[20:02:04] [main/INFO] [GradleStart]: Extra: [-Dfml.ignoreInvalidMinecraftCertificates=true]
[20:02:04] [main/INFO] [GradleStart]: Password found, attempting login
[20:02:04] [main/INFO]: Logging in with username & password
[20:02:05] [main/INFO] [GradleStart]: Login Succesful!
[20:02:05] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, [{"name":"twitch_access_token","value":"2utgone6a1douse86zz8m3ac39et5ch"}], --assetsDir, C:/Users/Sigurd/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --userType, mojang, --accessToken, {REDACTED}, --version, 1.7, --uuid, 31ee010964264ea0987165936649f6d2, --username, sigurd4, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, -Dfml.ignoreInvalidMinecraftCertificates=true, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[20:02:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:02:05] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:02:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[20:02:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:02:05] [main/INFO] [FML]: Forge Mod Loader version 8.99.124.1450 for Minecraft 1.8 loading
[20:02:05] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_25
[20:02:05] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[20:02:05] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:02:06] [main/WARN] [FML]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:02:06] [main/WARN] [FML]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:02:06] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:02:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[20:02:06] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[20:02:06] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[20:02:06] [main/INFO] [GradleStart]: Injecting location in coremod codechicken.core.asm.MCPDeobfuscationTransformer.LoadPlugin
[20:02:06] [main/INFO] [GradleStart]: Injecting location in coremod codechicken.lib.asm.CCLCorePlugin
[20:02:06] [main/INFO] [GradleStart]: Injecting location in coremod codechicken.core.launch.CodeChickenCorePlugin
[20:02:06] [main/INFO] [GradleStart]: Injecting location in coremod codechicken.lib.asm.CCLCorePlugin
[20:02:06] [main/INFO] [GradleStart]: Injecting location in coremod codechicken.nei.asm.NEICorePlugin
[20:02:06] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:02:06] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:02:06] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[20:02:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:02:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:02:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:02:06] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[20:02:09] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[20:02:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:02:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: Could not find methods.csv
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.parseConfDir(ObfMapping.java:150)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.getConfFiles(ObfMapping.java:96)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.<init>(ObfMapping.java:162)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping.loadMCPRemapper(ObfMapping.java:205)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping.<clinit>(ObfMapping.java:217)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.asm.MCPDeobfuscationTransformer.load(MCPDeobfuscationTransformer.java:113)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.asm.MCPDeobfuscationTransformer$LoadPlugin.injectData(MCPDeobfuscationTransformer.java:52)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:137)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[20:02:21] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at GradleStart.main(Unknown Source)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: Could not find methods.csv
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.parseConfDir(ObfMapping.java:150)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.getConfFiles(ObfMapping.java:96)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.<init>(ObfMapping.java:162)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping.loadMCPRemapper(ObfMapping.java:205)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping.<clinit>(ObfMapping.java:217)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.asm.MCPDeobfuscationTransformer.load(MCPDeobfuscationTransformer.java:113)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.asm.MCPDeobfuscationTransformer$LoadPlugin.injectData(MCPDeobfuscationTransformer.java:52)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:137)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[20:02:28] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at GradleStart.main(Unknown Source)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.RuntimeException: Could not find methods.csv
Exception in thread "main" [20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.parseConfDir(ObfMapping.java:150)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.getConfFiles(ObfMapping.java:96)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.<init>(ObfMapping.java:162)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping.loadMCPRemapper(ObfMapping.java:205)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping.<clinit>(ObfMapping.java:217)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.asm.MCPDeobfuscationTransformer.load(MCPDeobfuscationTransformer.java:113)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.asm.MCPDeobfuscationTransformer$LoadPlugin.injectData(MCPDeobfuscationTransformer.java:52)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:137)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at GradleStart.main(Unknown Source)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ExceptionInInitializerError
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.asm.MCPDeobfuscationTransformer.load(MCPDeobfuscationTransformer.java:113)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.asm.MCPDeobfuscationTransformer$LoadPlugin.injectData(MCPDeobfuscationTransformer.java:52)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:137)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at GradleStart.main(Unknown Source)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.RuntimeException: Failed to select mappings directory, set it manually in the config
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.getConfFiles(ObfMapping.java:107)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping$MCPRemapper.<init>(ObfMapping.java:162)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping.loadMCPRemapper(ObfMapping.java:205)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.asm.ObfMapping.<clinit>(ObfMapping.java:217)
[20:02:50] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 7 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
```

**Comment by GirafiStudios** [comment]
Put the methods.csv in that folder, which you already have directed it at.. :p

**Comment by sigurd4** [comment]
which methods.csv? i can't find one. where is it supposed to be?

**Comment by sigurd4** [comment]
this is how my conf folder looks like btw:
![image](https://cloud.githubusercontent.com/assets/11297695/9151653/6116d178-3e0a-11e5-924a-e1b7082068d5.png)

**Comment by GirafiStudios** [comment]
Example of where you would find the Methods.csv for 1.8: C:\Users\<user>\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_snapshot\<snapshot_number>

**Comment by sigurd4** [comment]
thank you so much! it works now!

**Comment by sigurd4** [comment]
this issue may now be closed

**Comment by GirafiStudios** [comment]
No problem :) You can close it yourself, since you created it.
