### ISSUE TITLE
core mod crash

### ISSUE THREAD

**Issue by cameronmyer0** [Chicken-Bones/CodeChickenCore#68]
MY EMAIL IS cameronmyer0@gmail.com

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MDECore-Core (mdecore-1.10.2-1.0.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.46-beta.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  CCCDeobfPlugin (unknown)
  DepLoader (BrandonsCore-1.10.2-2.1.0.36-universal.jar)
  MalisisCorePlugin (MalisisCore-1.10.2.jar)
  SimpleCore (Simple Quarry-1.9.4_1.0.0.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  ShetiPhian-ASM (ShetiPhianCore-1.10.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/23/16 7:42 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: codechicken/core/ClientUtils
    at codechicken.enderstorage.network.TankSynchroniser.tickEnd(TankSynchroniser.java:265)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_171_TankSynchroniser_tickEnd_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.core.ClientUtils
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Mac OS X (x86_64) version 10.10.5
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 453138088 bytes (432 MB) / 4214489088 bytes (4019 MB) up to 4214489088 bytes (4019 MB)
    JVM Flags: 25 total; -Xmx4G -Xms4G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2073 Optifine OptiFine_1.10.2_HD_U_C2 79 mods loaded, 78 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2073.jar) 
    UCHIJA  Forge{12.18.1.2073} [Minecraft Forge](forge-1.10.2-12.18.1.2073.jar) 
    UCHIJA  CodeChickenCore{2.1.8.79} [CodeChicken Core](minecraft.jar) 
    UCHIJA  actuallyadditions{1.10.2-r57} [Actually Additions](ActuallyAdditions-1.10.2-r57.jar) 
    UCHIJA  armorplus{1.9.4-3.1.10.0} [ArmorPlus](ArmorPlus1.9.4-3.1.10.0.jar) 
    UCHIJA  BBG{5.0.0} [BetterBedrockGen](BBG-1.9.4-5.0.0.jar) 
    UCHIJA  betterbuilderswands{0.6.5} [Better Builder's Wands](BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
    UCHIJA  BetterSprinting{1.1.5} [Better Sprinting](BetterSprinting  MC-1.10  v1.1.5.jar) 
    UCHIJA  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.0.1.jar) 
    UCHIJA  mantle{1.10-0.10.3.jenkins156} [Mantle](Mantle-1.10-0.10.3.jar) 
    UCHIJA  tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    UCHIJA  immersiveengineering{${version}} [Immersive Engineering](ImmersiveEngineering-0.10-38.jar) 
    UCHIJA  JEI{3.9.0.246} [Just Enough Items](jei_1.10.2-3.9.0.246.jar) 
    UCHIJA  blockdrops{1.0.10} [Block Drops](BlockDrops-1.10.2-1.0.10.jar) 
    UCHIJA  bookshelf{1.3.0.282} [Bookshelf](Bookshelf-1.10.2-1.3.0.282.jar) 
    UCHIJA  BrandonsCore{2.1.0} [Brandon's Core](BrandonsCore-1.10.2-2.1.0.36-universal.jar) 
    UCHIJA  cavern{1.0.8} [Cavern](Cavern_1.9.4-v1.0.8.jar) 
    UCHIJA  chancecubes{1.10-2.1.3.115} [Chance Cubes](ChanceCubes-1.10-2.1.3.115.jar) 
    UCHIJA  chisel{MC1.9.4-0.0.6.33} [Chisel](Chisel-Mod-1.10.2.jar) 
    UCHIJA  chiselsandbits{11.3} [Chisels & Bits](chiselsandbits-11.3.jar) 
    UCHIJA  ComputerCraft{1.80pr0} [ComputerCraft](ComputerCraft1.80pr0.jar) 
    UCHIJA  MineTweaker3{3.0.10} [MineTweaker 3](CraftTweaker-1.10.2-3.0.10.jar) 
    UCHIJA  cxlibrary{1.2.2} [CXLibrary](cxlibrary-1.10.2-1.2.2.jar) 
    UCHIJA  D3Core{1.3.0.59} [D³Core](D3Core-1.9.4-1.3.0.59.jar) 
    UCHIJA  D3Commands{1.3.0.36} [D3Commands](D3Commands-1.9.4-1.3.0.36.jar) 
    UCHIJA  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJA  darkutils{1.1.3.71} [Dark Utilities](DarkUtilities-1.10.2-1.1.3.71.jar) 
    UCHIJA  DimensionalResources{1.0.3} [DimensionalResources](Dimensional Resources v1.0.3.jar) 
    UCHIJA  DraconicEvolution{2.0.0} [Draconic Evolution](Draconic-Evolution-1.10.2-2.0.0.82-universal.jar) 
    UCHIJA  DurabilityShow{3.1.1} [Durability Show](Durability Show-1.9.4-3.1.1.jar) 
    UCHIJA  EnderStorage{2.1.3.71} [EnderStorage](Ender-Storage-Mod-1.10.2.jar) 
    UCHIJA  shetiphiancore{3.3.0} [ShetiPhian-Core](ShetiPhianCore-1.10.2.jar) 
    UCHIJA  endertanks{1.4.0} [EnderTanks](Ender-Tanks-Mod-1.10.2.jar) 
    UCHIJA  EnderBags{2.0.1} [EnderBags](EnderBags-1.9.4-2.0.0.jar) 
    UCHIJA  endercore{1.10.2-0.4.1.46-beta} [EnderCore](EnderCore-1.10.2-0.4.1.46-beta.jar) 
    UCHIJA  EnderIO{1.10.2-3.0.1.81_beta} [Ender IO](EnderIO-1.10.2-3.0.1.81_beta.jar) 
    UCHIJA  enderutilities{0.6.5-beta.1} [Ender Utilities](enderutilities-1.10.2-0.6.5-beta.1.jar) 
    UCHIJA  mdecore{1.10.2-1.0} [MattDahEpic Core](mdecore-1.10.2-1.0.jar) 
    UCHIJA  exchangeorb{1.10.2-1.0} [Exchange Orb](exchangeorb-1.10.2-1.0.jar) 
    UCHIJA  excore{1.6.2} [EXCore](Excore-1.6.2-1.10.2.jar) 
    UCHIJA  expandedbonemeal{1.0.0} [ExpandedBonemeal](Expanded-Bonemeal-Mod-1.10.2.jar) 
    UCHIJA  ezstorage{2.1.5} [EZ Storage 2](ezstorage-2.1.5.jar) 
    UCHIJA  FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-MC1.9.4-1.2.1.jar) 
    UCHIJA  ftfloocraft{1.7.5} [Floocraft](Floocraft-Mod-1.10.2.jar) 
    UCHIJA  forestry{5.1.8.189} [Forestry](Forestry-Mod-1.10.2.jar) 
    UCHIJA  llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded](LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
    UCHIJA  FEI{1.0.15} [Forever Enough Items](ForeverEnoughItems-1.0.15-1.10.2.jar) 
    UCHIJA  glass_shards{1.6.2} [Glass Shards](glass_shards_mc1.9.4-1.6.2.jar) 
    UCHIJA  hopperducts{1.4.7} [Hopper Ducts](hopperducts-mc1.9.4-1.4.7.jar) 
    UCHIJA  IC2{2.6.1-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.1-ex110.jar) 
    UCHIJA  InventoryPets{1.4.8.1} [Inventory Pets](inventorypets-1.10-1.4.8.1.jar) 
    UCHIJA  IronChest{7.0.6.794} [Iron Chest](ironchest-1.10.2-7.0.6.794.jar) 
    UCHIJA  itemscroller{0.5.1} [Item Scroller](itemscroller-1.10.2-0.5.1.jar) 
    UCHIJA  malisiscore{1.9.4-4.0.1} [MalisisCore](MalisisCore-1.10.2.jar) 
    UCHIJA  malisisdoors{1.9.4-5.0.1} [MalisisDoors](MalisisDoors-Mod-1.10.2.jar) 
    UCHIJA  MoreFurnaces{1.8.1} [More Furnaces](MoreFurnaces-1.10-1.8.1.jar) 
    UCHIJA  mysticalagriculture{1.0.0} [Mystical Agriculture](mysticalagriculture-1.0.2.jar) 
    UCHIJA  yurtmod{7.01} [Nomadic Tents](NomadicTents[1.10.2]-7.01.jar) 
    UCHIJA  placemod{3.8} [Placemod](placemod-3.8-1.10.2.jar) 
    UCHIJA  ProjectE{1.9.4-PE1.0.5B} [ProjectE](ProjectE-1.9.4-PE1.0.5B.jar) 
    UCHIJA  reborncore{2.5.4.1} [RebornCore](RebornCore-1.10.2-2.5.4.1-universal.jar) 
    UCHIJA  reborncore-mcmultipart{2.5.4.1} [reborncore-MCMultiPart](RebornCore-1.10.2-2.5.4.1-universal.jar) 
    UCHIJA  redstonepaste{1.7.4} [Redstone Paste](redstonepaste-mc1.9.4-1.7.4.jar) 
    UCHIJA  reinforcedTools{1.4.1} [ReinforcedTools](ReinforcedTools-1.5.0-1.10.2.jar) 
    UCHIJA  rftools{5.09} [RFTools](rftools-1.10-5.09.jar) 
    UCHIJA  rftoolsdim{4.30beta46} [RFTools Dimensions](rftoolsdim-1.10-4.30beta46.jar) 
    UCHIJA  Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJA  AS_Ruins{16.2} [Ruins Spawning System](Ruins-Mod-1.10.2.jar) 
    UCHIJA  simplequarry{1.9.4_1.0.0} [Simple Quarry](Simple Quarry-1.9.4_1.0.0.jar) 
    UCHIJA  supercraftingframe{1.2.0.84} [Super Crafting Frame](Super-Crafting-Frame-Mod-1.10.2.jar) 
    UCHIJA  lteleporters{1.1.3} [Lemon's Simple Teleporters](teleporters-1.1.3.jar) 
    UCHIJA  VeinMiner{0.34.0_1.9-58ffb13} [Vein Miner](VeinMiner-0.34.0-1.9r565+58ffb13.jar) 
    UCHIJA  VeinMinerModSupport{0.34.0_1.9-58ffb13} [Mod Support](VeinMiner-0.34.0-1.9r565+58ffb13.jar) 
    UCHIJA  WailaHarvestability{1.1.8} [Waila Harvestability](WailaHarvestability-mc1.10.2-1.1.8.jar) 
    UCHIJA  warpscrolls{1.0} [warpscrolls](Warp Scrolls 1.9.4 1.0.2.jar) 
    UCHIJA  worldhandler{3.8} [World Handler Gui](WorldHandler-1.10-3.8.jar) 
    UCHIJA  wuestUtilities{1.10.2} [Wuest Utilities](wuestUtilities-1.10.2.0.jar) 
    UD  mdecore-core{1.0} [MDE Core - ASM Tweaks](minecraft.jar) 
    Loaded coremods (and transformers): 
MDECore-Core (mdecore-1.10.2-1.0.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)

EnderCorePlugin (EnderCore-1.10.2-0.4.1.46-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
CCCDeobfPlugin (unknown)

DepLoader (BrandonsCore-1.10.2-2.1.0.36-universal.jar)

MalisisCorePlugin (MalisisCore-1.10.2.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
SimpleCore (Simple Quarry-1.9.4_1.0.0.jar)
  com.mrdimka.simplequarry.core.SimpleClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
ShetiPhian-ASM (ShetiPhianCore-1.10.2.jar)
  shetiphian.core.asm.ClassTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
CodeChickenCore: ignoreInvalidMCVersion state: false
D3Core: Debug: false Silliness: true AprilFools: true PastPost:true
EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
              * Optifine is installed. This is NOT supported.
             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
Detailed RF API diagnostics:
              * RF API class 'EnergyStorage' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/EnergyStorage.class
              * RF API class 'IEnergyConnection' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyConnection.class
              * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
              * RF API class 'IEnergyHandler' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyHandler.class
              * RF API class 'IEnergyProvider' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyProvider.class
              * RF API class 'IEnergyReceiver' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyReceiver.class
              * RF API class 'IEnergyStorage' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/IEnergyStorage.class
              * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/TileEnergyHandler.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/christiemyer/Library/Application%20Support/minecraft/mods/BrandonsCore-1.10.2-2.1.0.36-universal.jar!/cofh/api/energy/TileEnergyHandler.class

Launched Version: 1.10.2
LWJGL: 2.9.2
OpenGL: ATI Radeon HD 4670 OpenGL Engine GL version 2.1 ATI-10.0.35, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Faithful 1.10.2.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz
```

**Comment by RedDemon999** [comment]
@cameronmyer0  I just released a video showing you how to fix this error go check it out for you can fix it.

https://www.youtube.com/watch?v=BaVBrDxwk9U
