### ISSUE TITLE
Unable to initialize 

### ISSUE THREAD

**Issue by 0x000NULL** [Chicken-Bones/CodeChickenCore#89]
When I try to start Minecraft,1.7.10 and latest forge, I get the log as shown below. Here is a list of the mods being used also.

The game is running. Please wait.
[14:49:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:49:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:49:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[14:49:11] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[14:49:11] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.11.6, installed at /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[14:49:11] [main/INFO] [FML]: [AppEng] Core Init
[14:49:11] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:49:11] [main/INFO] [FML]: Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.0.1.jar
[14:49:11] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: cofh/asm/LoadingPlugin : Unsupported major.minor version 51.0
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.defineClass1(Native Method)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.security.AccessController.doPrivileged(Native Method)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.Class.forName0(Native Method)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.Class.forName(Class.java:249)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:49:12] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/BrantleyLytle/Desktop/./instances/Server/minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: cofh/asm/LoadingPlugin : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
    at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
    at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: cofh/asm/LoadingPlugin : Unsupported major.minor version 51.0
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.defineClass1(Native Method)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.security.AccessController.doPrivileged(Native Method)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
Exception in thread "main" [14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.Class.forName0(Native Method)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at java.lang.Class.forName(Class.java:249)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[14:49:12] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Process ended with code: 1

**Comment by 0x000NULL** [comment]
The mods used are:
mcp, FML, Forge, kimagine, appliedenergistics2-core, Aroma1997Core, CartFixes, CodeChickenCore, Micdoodlecore, NotEnoughItems, OpenComputers|Core, <CoFH ASM>, Treecapitator, lightsabers, AgriCraft, aiimprovements, appliedenergistics2, ArchimedesShipsPlus, Aroma1997CoreHelper, Aroma1997sDimension, bttfmod, barrierblock, bdlib, betterbuilderswands, betterloadingscreen, BiblioCraft, BigReactors, BiomesOPlenty, BrandonsCore, Bricks, CarpentersBlocks, cfm, ChickenChunks, chisel, CoFHCore, CompactSolars, ComputerCraft, crashlogadditions, customnpcs, DeathChest, PTRModelLib, props, DraconicEvolution, dsurround, Dynmap, Eln, EnderStorage, enderutilities, etfuturum, ExtraPlanets, ExtraUtilities, fastleafdecay, flansmod, FTBL, FTBU, GalacticraftMars, GalacticraftCore, advgenerators, hardcorewither, IC2NuclearControl, IC2, inventorytweaks, ironbackpacks, IronChest, IronFence, itlt, JABBA, journeymap, LEDLighting, Mantle, mo, MekanismGenerators, MekanismTools, Mekanism, Monoblocks, MonoblocksMultipart, MovingWorld, netherportalfix, recipehandler, numina, Obsidian, OpenComputers, openmodularturrets, harvestcraft, PneumaticCraft, PowerConverters3, progressiveautomation, ProjRed|Core, ProjRed|Compatibility, ProjRed|Fabrication, ProjRed|Integration, ProjRed|Transmission, ProjRed|Illumination, ProjRed|Expansion, ProjRed|Transportation, ProjRed|Exploration, RadixCore, Railcraft, railcraft_cos, Records, RedstonePasteMod, corerm, Roguelike, rc, RTG, SpecialAI, StevesCarts, StorageDrawers, fiskutils, fiskheroes, supertramp, TConstruct, Techguns, camping, kitchen, ThermalExpansion, ThermalFoundation, TMechworks, VeinMiner, VeinMinerModSupport, Waila, WailaHarvestability, wildmobsmod, worldedit, bspkrsCore, ForgeMicroblock, ForgeMultipart, McMultipart, MCFrames, ForgeRelocation, RelocationFMP, MrTJPCoreMod
